image: alekzonder/puppeteer:latest

cache:
  paths:
  - node_modules/

stages:
  - test

test & build:
  stage: test
  script:
    - npm install
    - npm run lint
    # - npm run test:ci
    # - npm run e2e:ci
    - npm run build:devtools
  only:
    - master
    - develop
  artifacts:
    paths:
    - dist
